version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-latest"

conda:
  environment: doc/environment_rtd.yml

python:
  install:
    - requirements: doc/requirements_rtd.txt
    - method: pip
      path: .
      
sphinx:
  configuration: doc/source/conf.py
