version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-latest"

conda:
  environment: docs/environment_rtd.yml

python:
  install:
    - method: pip
      path: .
      
sphinx:
  configuration: docs/source/conf.py
